<?php

declare(strict_types=1);

namespace Salix\Cms\State;

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProcessorInterface;
use Salix\Cms\Entity\ContentPage;
use Salix\Cms\Service\SlugGenerator;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\DependencyInjection\Attribute\AsDecorator;
use Symfony\Component\DependencyInjection\Attribute\AutowireDecorated;

/**
 * Wraps API Platform's Doctrine persist processor to:
 *  - fill a blank slug from the title (so the slug is optional on the API), and
 *  - close the check-then-insert race on the slug's unique constraint by retrying with a
 *    fresh suffix when a concurrent insert wins.
 *
 * @implements ProcessorInterface<mixed, mixed>
 */
#[AsDecorator('api_platform.doctrine.orm.state.persist_processor')]
final readonly class ContentPagePersistProcessor implements ProcessorInterface
{
    private const int MAX_ATTEMPTS = 5;

    /**
     * @param ProcessorInterface<mixed, mixed> $decorated
     */
    public function __construct(
        #[AutowireDecorated] private ProcessorInterface $decorated,
        private SlugGenerator $slugGenerator,
        private ManagerRegistry $registry,
    ) {
    }

    public function process(mixed $data, Operation $operation, array $uriVariables = [], array $context = []): mixed
    {
        if (!$data instanceof ContentPage) {
            return $this->decorated->process($data, $operation, $uriVariables, $context);
        }

        $isNew = null === $data->getId();
        $autoGenerated = $this->isBlank($data->getSlug());

        if ($autoGenerated) {
            $data->setSlug($this->slugGenerator->generateUniqueSlug((string) $data->getTitle(), $data->getId()));
        }

        $attempt = 1;
        while (true) {
            try {
                return $this->decorated->process($data, $operation, $uriVariables, $context);
            } catch (UniqueConstraintViolationException $e) {
                // Only a freshly-created page whose slug we generated can be safely re-suffixed.
                // Client-chosen slugs and updates are surfaced as-is (UniqueEntity already guards them).
                if (!$isNew || !$autoGenerated || $attempt >= self::MAX_ATTEMPTS) {
                    throw $e;
                }

                ++$attempt;
                // The failed flush closed the EntityManager; start a clean one before retrying.
                $this->registry->resetManager();
                $data->setSlug($this->slugGenerator->generateUniqueSlug((string) $data->getTitle()));
            }
        }
    }

    private function isBlank(?string $slug): bool
    {
        return null === $slug || '' === trim($slug);
    }
}
