<?php

declare(strict_types=1);

namespace Salix\Cms\Service;

use Salix\Cms\Entity\ContentPage;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;

final readonly class ContentPagePersister
{
    private const int MAX_ATTEMPTS = 5;

    public function __construct(
        private SlugGenerator $slugGenerator,
        private ManagerRegistry $registry,
    ) {
    }

    public function save(ContentPage $page): void
    {
        $isNew = null === $page->getId();
        $autoGenerated = $this->isBlank($page->getSlug());

        if ($autoGenerated) {
            $page->setSlug($this->slugGenerator->generateUniqueSlug((string) $page->getTitle(), $page->getId()));
        }

        $attempt = 1;
        while (true) {
            $manager = $this->registry->getManagerForClass(ContentPage::class);
            \assert($manager instanceof EntityManagerInterface);

            try {
                $manager->persist($page);
                $manager->flush();

                return;
            } catch (UniqueConstraintViolationException $e) {
                // Only a freshly-created page whose slug we generated can be safely re-suffixed.
                // Client-chosen slugs and updates are surfaced as-is (UniqueEntity already guards them).
                if (!$isNew || !$autoGenerated || $attempt >= self::MAX_ATTEMPTS) {
                    throw $e;
                }

                ++$attempt;
                $this->registry->resetManager();
                $page->setSlug($this->slugGenerator->generateUniqueSlug((string) $page->getTitle()));
            }
        }
    }

    private function isBlank(?string $slug): bool
    {
        return null === $slug || '' === trim($slug);
    }
}
