services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $uploadsDir: '%kernel.project_dir%/public/uploads/images'

    Salix\Cms\:
        resource: '../src/'
        exclude:
            - '../src/SalixCmsBundle.php'
            - '../src/Entity/'
